name: Flutter and Dart CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6  # Change to the desired Flutter version

      - name: Install Dependencies
        run: flutter pub get

     # - name: Analyze Dart Code
      #  run: dart analyze

     # - name: Run Flutter Tests
      #  run: flutter test
